// , JUST CREATE THIS FILE FOR NOw
//         {
//             "name": "GOOG",
//             "open": 154.64,
//             "high": 156.36,
//             "low": 152.68,
//             "close": 154.46,
//             "volume": 84809500,
//             "adj_high": null,
//             "adj_low": null,
//             "adj_close": 154.46,
//             "adj_open": null,
//             "adj_volume": null,
//             "split_factor": 1,
//             "dividend": 0,
//             "symbol": "AAPL",
//             "exchange": "XNAS",
//             "date": "2022-09-08T00:00:00+0000"
//         },
//         {
//             "name": "company 1",
//             "open": 157.34,
//             "high": 158.74,
//             "low": 153.6,
//             "close": 153.72,
//             "volume": 101407100,
//             "adj_high": null,
//             "adj_low": null,
//             "adj_close": 153.72,
//             "adj_open": null,
//             "adj_volume": null,
//             "split_factor": 1,
//             "dividend": 0,
//             "symbol": "AAPL",
//             "exchange": "XNAS",
//             "date": "2022-09-21T00:00:00+0000"
//         },
//         {
//             "name": "company 2",
//             "open": 153.4,
//             "high": 158.08,
//             "low": 153.08,
//             "close": 156.9,
//             "volume": 107547900,
//             "adj_high": null,
//             "adj_low": null,
//             "adj_close": 156.9,
//             "adj_open": null,
//             "adj_volume": null,
//             "split_factor": 1,
//             "dividend": 0,
//             "symbol": "AAPL",
//             "exchange": "XNAS",
//             "date": "2022-09-20T00:00:00+0000"
//         },
//         {
//             "name": "company 3",
//             "open": 149.31,
//             "high": 154.56,
//             "low": 149.1,
//             "close": 154.48,
//             "volume": 81328800,
//             "adj_high": null,
//             "adj_low": null,
//             "adj_close": 154.48,
//             "adj_open": null,
//             "adj_volume": null,
//             "split_factor": 1,
//             "dividend": 0,
//             "symbol": "AAPL",
//             "exchange": "XNAS",
//             "date": "2022-09-19T00:00:00+0000"
//         },
//         {
//             "name": "company 4",
//             "open": 151.21,
//             "high": 151.35,
//             "low": 148.37,
//             "close": 150.7,
//             "volume": 162157000,
//             "adj_high": null,
//             "adj_low": null,
//             "adj_close": 150.7,
//             "adj_open": null,
//             "adj_volume": null,
//             "split_factor": 1,
//             "dividend": 0,
//             "symbol": "AAPL",
//             "exchange": "XNAS",
//             "date": "2022-09-16T00:00:00+0000"
//         },
//         {
//             "name": "company 3",
//             "open": 154.65,
//             "high": 155.24,
//             "low": 151.38,
//             "close": 152.37,
//             "volume": 90263300,
//             "adj_high": null,
//             "adj_low": null,
//             "adj_close": 152.37,
//             "adj_open": null,
//             "adj_volume": null,
//             "split_factor": 1,
//             "dividend": 0,
//             "symbol": "AAPL",
//             "exchange": "XNAS",
//             "date": "2022-09-15T00:00:00+0000"
//         }